import type { Locale } from "@/lib/i18n";

/**
 * **The public address, and it is not configurable.**
 *
 * A static export bakes absolute URLs into `og:url`, `canonical` and the
 * sitemap at build time, so a build that guessed the wrong host would publish
 * links to a site nobody serves. This one is deployed to `docs.algojudge.pl`
 * and nowhere else, which makes a constant the honest form: an environment
 * variable would suggest a choice the deployment does not have.
 */
export const SITE_URL = "https://docs.algojudge.pl";

export const SITE_NAME = "AlgoJudge";

/** The project's own site. The documentation is a subdomain of it, not a rival. */
export const HOMEPAGE = "https://algojudge.pl/";

/**
 * **Which version of the product this documentation describes.**
 *
 * `released` was `null` until 2026-09-08, which was the honest state while no
 * product repository carried a `v*` tag. Five of them do now, and
 * `npm run snapshot -- v0.1` cut the directories that day — 188 files across
 * all five sections — so this names a version that exists.
 *
 * The accepted decision of 2026-08-09 says a version directory is created on
 * release day and never retroactively. **So this value and the directories move
 * together**: nothing sets it — `scripts/snapshot.mjs` does not touch this file
 * — and `lib/layout.shared.tsx` renders it under the title on every page, so a
 * released site left at `null` says *unreleased* on all 266 of them.
 */
export const documented: { released: string | null; label: Record<Locale, string> } = {
    released: "0.1",
    // **Unreachable while `released` is set**, and kept for the next line that
    // has not been cut yet. Short enough to sit on one line beside the name:
    // "przed wydaniem" wrapped and pushed the title onto two.
    label: { en: "unreleased", pl: "przed 0.1" },
};

/**
 * Appended to every page title. **Not `SITE_NAME`**: that one names the product,
 * and is what `applicationName` and the card's alt text say. This names the
 * site, which is a different thing on a different domain.
 */
export const TITLE_SUFFIX = "AlgoJudge Docs";

/**
 * **The pages this application links from code rather than from a page.**
 *
 * `components/licence-note.tsx` sends a reader here for the licence split, and
 * `scripts/check-links.mjs` reads every `.mdx` file - so this address is the one
 * internal link in the site that no page contains and nothing would notice
 * breaking. Naming it here is what lets the check reach it.
 */
export const linkedFromCode = (locale: string) => [`/${locale}/source`];

/** 1200×630, generated by `npm run og` and committed. */
export const OG_IMAGE = "/og.png";

export const site: Record<Locale, { name: string; description: string }> = {
    en: {
        name: "AlgoJudge documentation",
        description:
            "AlgoJudge is open-source, self-hosted software for programming contests and courses, with automatic evaluation of submitted solutions. Install it, run a contest, and build against its API.",
    },
    pl: {
        name: "Dokumentacja AlgoJudge",
        description:
            "AlgoJudge to otwartoźródłowe oprogramowanie self-hosted do organizacji zawodów i kursów programistycznych z automatycznym ocenianiem przesłanych rozwiązań.",
    },
};

/**
 * **Two spellings of the same thing, and they are not interchangeable.**
 *
 * `hreflang` takes BCP-47 with a hyphen; `og:locale` takes Facebook's
 * `language_TERRITORY` with an underscore, and a hyphen there is ignored rather
 * than reported. British English is the register the pages are written in.
 */
export const hreflang: Record<Locale, string> = { en: "en-GB", pl: "pl-PL" };
export const ogLocale: Record<Locale, string> = { en: "en_GB", pl: "pl_PL" };
