import type { Locale } from "@/lib/i18n";

/**
 * **The public address, and it is not configurable.**
 *
 * A static export bakes absolute URLs into `og:url`, `canonical` and the
 * sitemap at build time, so a build that guessed the wrong host would publish
 * links to a site nobody serves. This one is deployed to `docs.algojudge.pl`
 * and nowhere else, which makes a constant the honest form: an environment
 * variable would suggest a choice the deployment does not have.
 */
export const SITE_URL = "https://docs.algojudge.pl";

export const SITE_NAME = "AlgoJudge";

/** 1200×630, generated by `npm run og` and committed. */
export const OG_IMAGE = "/og.png";

export const site: Record<Locale, { name: string; description: string }> = {
    en: {
        name: "AlgoJudge documentation",
        description:
            "AlgoJudge is open-source, self-hosted software for programming contests and courses, with automatic evaluation of submitted solutions. Install it, run a contest, and build against its API.",
    },
    pl: {
        name: "Dokumentacja AlgoJudge",
        description:
            "AlgoJudge to otwarte, samodzielnie hostowane oprogramowanie do konkursów i kursów programistycznych, z automatyczną oceną nadsyłanych rozwiązań. Instalacja, prowadzenie konkursu i praca z API.",
    },
};

/**
 * **Two spellings of the same thing, and they are not interchangeable.**
 *
 * `hreflang` takes BCP-47 with a hyphen; `og:locale` takes Facebook's
 * `language_TERRITORY` with an underscore, and a hyphen there is ignored rather
 * than reported. British English is the register the pages are written in.
 */
export const hreflang: Record<Locale, string> = { en: "en-GB", pl: "pl-PL" };
export const ogLocale: Record<Locale, string> = { en: "en_GB", pl: "pl_PL" };
